### ISSUE TITLE
User data in checkout

### ISSUE THREAD

**Issue by kejso** [backdrop-contrib/basic_cart#2]
Hi, 

I just want to ask if its possible to prefill the fields Name and Email with current logged in user name and email? Is there some code which I can use?

Thank you!

**Comment by robertgarrigos** [comment]
Hi @kejso, email is already being filled in. The name is not, as there is not such a field in backdrop as default. There is Username, but I don't know if it is that what you want.

**Comment by robertgarrigos** [comment]
Closing this. Please, open it if you feel so.
