### ISSUE TITLE
offer to maintain this module

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/basic_cart#3]
I just applied to the contrib group as I'm porting (https://github.com/robertgarrigos/usertabs) and creating some new modules (a payment gateway) for backdrop. I'm planning to use this module, basic_cart, in one  of my sites and would like to offer myself to co-mainatin it, as it seems no one is doing it right now and found that it's not working with latest backdrop version.

**Comment by klonos** [comment]
"pinging" @biolithic

**Comment by robertgarrigos** [comment]
It's been some three weeks already without any answer from @biolithic . I tried to contact him also thru linkedin with no luck. What's the process now to become a maintainer of basic_cart module?

**Comment by serundeputy** [comment]
Process: https://github.com/backdrop-ops/contrib#user-content-abandoned-projects

**Comment by serundeputy** [comment]
@klonos would you mind adding @robertgarrigos to the readme.md as maintainer of this module?

**Comment by klonos** [comment]
Done! (also renamed the file to `README.md` and did some very basic clean up): https://github.com/backdrop-contrib/basic_cart/commit/d5eea5f6ad4ae0d29f42abd76b071d5cc803e6f0#diff-04c6e90faac2675aa89e2176d2eec7d8R148

Good luck @robertgarrigos and do let me know if there is anything else I can help with.
