### ISSUE TITLE
Offer to Co-Maintain

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/basic_cart#5]
Hi @biolithic, I know there is also https://github.com/biolithic/basic_cart_plus, but in my situation I would prefer the smaller use-case of this module, basic_cart. In trying out this module it has a few PHP notices and errors. Would it be possible for me to help maintain the project and clean up some of these issues?

**Comment by robertgarrigos** [comment]
You are more than welcome, @quicksketch.

**Comment by quicksketch** [comment]
Thanks @robertgarrigos! I should have come back to this earlier. I ended up not using a cart module and integrated all cart-like functionality with Stripe instead. Since I am no longer using this module I don't think I'll have the time or interest to maintain it. Closing this out.
